spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/"
      database: "notifHub"

mongock:
  migration-scan-package: "com.example.mongotestkotlin.config.db.migration"
  transaction-enabled: true
